### ISSUE TITLE
conversion error

### ISSUE THREAD

**Issue by AlexDigitalWorks** [markondej/cpp-icmplib#4]
Hello, 
I get an error when I try to convert a string to IPAddress :
C:\01_Files\$$\test.cpp:22: erreur : No viable conversion from 'QString' to 'const IPAddress'
Does anyone knows how to get through this ?

**Comment by markondej** [comment]
Try:
```
QString ip("127.0.0.1");
icmplib::IPAddress ip_v4(ip.toStdString());
```

**Comment by AlexDigitalWorks** [comment]
it worked! thanks!
