### ISSUE TITLE
Timout should be in milliseconds, not seconds

### ISSUE THREAD

**Issue by C8lCat** [markondej/cpp-icmplib#5]
In the while loop, the if-statement only succeeds after 1 second, even if the timeout is less than 1 second, like 0.03, because std::chrono::duration_cast<std::chrono::seconds>(end - start).count() doesn't return a floating point number.

                    if (!recv) {
                        if (static_cast<unsigned>(std::chrono::duration_cast<std::chrono::seconds>(end - start).count()) > timeout) {
                            break;
                        }
                        std::this_thread::sleep_for(std::chrono::microseconds(ICMPLIB_NOP_DELAY));
                        continue;
                    }

std::chrono::duration_cast<std::chrono::seconds>(end - start).count() should be changed to std::chrono::duration_cast<std::chrono::milliseconds>(end - start).count() and also the timeout. The default timeout of 60 seconds is way too much. 100 milliseconds is reasonable.

**Comment by markondej** [comment]
I added changes so timeout is given in milliseconds with default value 1000ms
